# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        user_db:
            entity: { class: com\BackEndBundle\Entity\User, property: user }            

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path:  /admin/login
                check_path:  /check
            logout:
                path:   /logout
                target: /admin/login
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/backend, roles: ROLE_ADMIN, requires_channel: http } 
        - { path: ^/metronic, roles: ROLE_ADMIN, requires_channel: http } 
